"""hermes_api.py — OpenAI-compatible HTTP API for the Hermes fleet.

Disabled by default. Enable via Settings → Talent Config → hermes_api.

Exposes Talon as an OpenAI-style endpoint so external agents (the Hermes
fleet) can converse with Talon and issue commands using any stock OpenAI
client. Every chat message is routed through assistant.process_command(),
so commands hit talents, questions fall through to conversation/RAG, and
job-pipeline data is reachable via the normal command surface.

Endpoints:
  POST /v1/chat/completions   main entry (supports stream=true as one chunk)
  GET  /v1/models             model discovery (many clients probe this)
  GET  /health                unauthenticated liveness probe, no info leak

Security model (per-client keys):
  - Each fleet member gets its own bearer key, generated by "add hermes
    client <name>". The plaintext key is shown ONCE; only its SHA-256 hash
    is stored (config/hermes_clients.json, gitignored). Revoke individually
    with "revoke hermes client <name>".
  - Auth uses constant-time comparison; failures are logged with source IP.
  - Binds default to 127.0.0.1 only. Additional addresses are an explicit
    config choice. Plain HTTP — keep it on loopback or a trusted segment.
  - Inbound text passes the same semantic-injection filter as the Signal
    remote before reaching process_command().

Client usage (any OpenAI SDK):
  client = OpenAI(base_url="http://<host>:<port>/v1", api_key="<client key>")
  client.chat.completions.create(model="talon", messages=[...])
"""

import hashlib
import hmac
import json
import os
import secrets
import threading
import time
from datetime import datetime
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from talents.base import BaseTalent

import logging
log = logging.getLogger(__name__)

_MAX_BODY_BYTES = 256 * 1024        # request size cap
_KEY_PREFIX = "th-"                 # talon-hermes key namespace
_MODEL_ID = "talon"


class HermesApiTalent(BaseTalent):
    name = "hermes_api"
    description = "Expose an OpenAI-compatible API so the Hermes fleet can command and converse with Talon"
    keywords = [
        "hermes status", "hermes api", "hermes client", "hermes clients",
        "add hermes", "revoke hermes", "list hermes",
    ]
    examples = [
        "what's the hermes api status",
        "add hermes client scout",
        "revoke hermes client scout",
        "list hermes clients",
    ]
    priority = 49   # near signal_remote (48); distinctive keyword, low collision

    def get_config_schema(self) -> dict:
        return {
            "fields": [
                {"key": "enabled",
                 "label": "Enable Hermes API",
                 "type": "bool",
                 "default": False},
                {"key": "bind_addresses",
                 "label": "Bind Addresses (host:port, comma-separated)",
                 "type": "string",
                 "default": "127.0.0.1:8770",
                 "help": (
                     "One listener per entry, e.g. "
                     "'127.0.0.1:8770, 192.168.1.20:8770'. Loopback-only by "
                     "default; adding a LAN address exposes the API to that "
                     "segment (plain HTTP, bearer-key auth)."
                 )},
                {"key": "clients_file",
                 "label": "Client Keys File",
                 "type": "string",
                 "default": os.path.join("config", "hermes_clients.json"),
                 "help": (
                     "Per-client key store. Only SHA-256 hashes are kept; "
                     "plaintext keys are shown once at creation."
                 )},
            ]
        }

    # ── Lifecycle ──────────────────────────────────────────────────

    def __init__(self):
        super().__init__()
        self._assistant = None
        self._servers: list[tuple[ThreadingHTTPServer, threading.Thread]] = []
        self._cmd_lock = threading.Lock()   # serialize process_command calls
        self._lock = threading.Lock()       # stats
        self._stats: dict = {
            "requests_served": 0,
            "auth_failures": 0,
            "last_client": None,
            "last_seen": None,
        }

    def set_assistant(self, assistant) -> None:
        """Called by TalonAssistant.__init__() after talent discovery."""
        self._assistant = assistant
        # Same dual-flag gate as signal_remote: set_assistant() runs for every
        # talent regardless of the top-level toggle, so both must be on.
        if self.enabled and self.talent_config.get("enabled", False):
            self._start_servers()

    def update_config(self, config: dict) -> None:
        """Called by GUI when the user saves talent config changes."""
        super().update_config(config)
        if self.enabled and config.get("enabled", False):
            self._restart_servers()
        else:
            self._stop_servers()

    def can_handle(self, command: str) -> bool:
        return self.keyword_match(command)

    # ── Server lifecycle ───────────────────────────────────────────

    def _parse_binds(self) -> list[tuple[str, int]]:
        """Parse the bind_addresses config into (host, port) pairs."""
        raw = self.talent_config.get("bind_addresses", "127.0.0.1:8770")
        binds: list[tuple[str, int]] = []
        for entry in str(raw).split(","):
            entry = entry.strip()
            if not entry:
                continue
            host, sep, port_s = entry.rpartition(":")
            if not sep or not host:
                log.error(f"[Hermes] Bad bind address {entry!r} — "
                          f"expected host:port. Skipping.")
                continue
            try:
                port = int(port_s)
            except ValueError:
                log.error(f"[Hermes] Bad port in {entry!r}. Skipping.")
                continue
            binds.append((host, port))
        return binds

    def _start_servers(self) -> None:
        if self._servers:
            return  # already running
        binds = self._parse_binds()
        if not binds:
            log.error("[Hermes] No valid bind addresses configured; "
                      "API not started.")
            return

        talent = self

        class _Handler(_HermesHandler):
            _talent = talent

        for host, port in binds:
            try:
                srv = ThreadingHTTPServer((host, port), _Handler)
                srv.daemon_threads = True
            except OSError as e:
                log.error(f"[Hermes] Cannot bind {host}:{port}: {e}")
                continue
            th = threading.Thread(
                target=srv.serve_forever, daemon=True,
                name=f"hermes-api-{host}:{port}")
            th.start()
            self._servers.append((srv, th))
            log.info(f"[Hermes] API listening on http://{host}:{port}/v1")

        if not self._servers:
            log.error("[Hermes] All binds failed; API not running.")

    def _stop_servers(self) -> None:
        servers, self._servers = self._servers, []
        for srv, _th in servers:
            try:
                srv.shutdown()
                srv.server_close()
            except Exception:
                pass
        if servers:
            log.info("[Hermes] API stopped.")

    def _restart_servers(self) -> None:
        self._stop_servers()
        self._start_servers()

    # ── Client key store ───────────────────────────────────────────

    def _clients_path(self) -> str:
        return self.talent_config.get(
            "clients_file", os.path.join("config", "hermes_clients.json"))

    def _load_clients(self) -> dict:
        try:
            with open(self._clients_path(), encoding="utf-8") as f:
                data = json.load(f)
            return data if isinstance(data, dict) else {}
        except (FileNotFoundError, json.JSONDecodeError):
            return {}

    def _save_clients(self, clients: dict) -> None:
        path = self._clients_path()
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(clients, f, indent=2)

    def add_client(self, name: str) -> str:
        """Create (or rotate) a client key. Returns the plaintext key —
        the only time it is ever available."""
        key = _KEY_PREFIX + secrets.token_hex(24)
        clients = self._load_clients()
        clients[name] = {
            "key_hash": hashlib.sha256(key.encode()).hexdigest(),
            "created": datetime.now().isoformat(timespec="seconds"),
            "enabled": True,
        }
        self._save_clients(clients)
        log.info(f"[Hermes] Client key created/rotated for {name!r}.")
        return key

    def revoke_client(self, name: str) -> bool:
        clients = self._load_clients()
        if name not in clients:
            return False
        del clients[name]
        self._save_clients(clients)
        log.info(f"[Hermes] Client {name!r} revoked.")
        return True

    def authenticate(self, bearer: str) -> str | None:
        """Return the client name for a presented key, or None."""
        presented = hashlib.sha256(bearer.encode()).hexdigest()
        for name, rec in self._load_clients().items():
            if not isinstance(rec, dict) or not rec.get("enabled", True):
                continue
            if hmac.compare_digest(presented, rec.get("key_hash", "")):
                return name
        return None

    # ── Request → Talon bridge (called from handler threads) ──────

    def handle_chat(self, client_name: str, user_text: str) -> tuple[str, str]:
        """Run one chat message through Talon.

        Returns (content, finish_reason). Serialized behind _cmd_lock —
        the LLM backend is single-user, so concurrent fleet requests queue.
        """
        # Same semantic-injection gate as the Signal remote: fleet input is
        # foreign data even though it's authenticated.
        try:
            from core.security import get_security_filter as _gsf
            _sf = _gsf()
        except Exception:
            _sf = None
        if _sf:
            blocked, _alert = _sf.check_semantic_input(user_text, "hermes_in")
            if blocked:
                log.info(f"[Hermes] Blocked by semantic filter "
                         f"(client {client_name!r}): {user_text!r}")
                return ("Request blocked by Talon's security policy.",
                        "content_filter")

        if self._assistant is None:
            return ("Talon is still starting up; try again shortly.", "stop")

        with self._cmd_lock:
            result = self._assistant.process_command(
                user_text,
                speak_response=False,
                _executing_rule=True,
                command_source="hermes",
            )
        response = ((result or {}).get("response") or "").strip()

        with self._lock:
            self._stats["requests_served"] += 1
            self._stats["last_client"] = client_name
            self._stats["last_seen"] = datetime.now().isoformat(
                timespec="seconds")

        return (response or "(no response)", "stop")

    def note_auth_failure(self, ip: str) -> None:
        with self._lock:
            self._stats["auth_failures"] += 1
        log.warning(f"[Hermes] Auth failure from {ip}.")

    # ── Execute (status / client management) ──────────────────────

    def execute(self, command: str, context: dict) -> dict:
        cmd = command.lower()
        running = bool(self._servers)

        # -- add hermes client <name> --
        if "add" in cmd or "create" in cmd or "new" in cmd:
            name = self._extract_client_name(command)
            if not name:
                return {"success": False,
                        "response": "Give the client a name: "
                                    "'add hermes client scout'.",
                        "actions_taken": []}
            key = self.add_client(name)
            return {
                "success": True,
                "response": (
                    f"Client '{name}' created. Its API key (shown once, "
                    f"store it now):\n\n{key}\n\n"
                    f"Point an OpenAI client at http://<bind>/v1 with this "
                    f"key; model id is '{_MODEL_ID}'."
                ),
                "actions_taken": [f"hermes client {name} created"],
            }

        # -- revoke hermes client <name> --
        if "revoke" in cmd or "remove" in cmd or "delete" in cmd:
            name = self._extract_client_name(command)
            if not name:
                return {"success": False,
                        "response": "Which client? "
                                    "'revoke hermes client scout'.",
                        "actions_taken": []}
            if self.revoke_client(name):
                return {"success": True,
                        "response": f"Client '{name}' revoked.",
                        "actions_taken": [f"hermes client {name} revoked"]}
            return {"success": False,
                    "response": f"No client named '{name}'.",
                    "actions_taken": []}

        # -- list hermes clients --
        if "list" in cmd or "clients" in cmd:
            clients = self._load_clients()
            if not clients:
                return {"success": True,
                        "response": "No Hermes clients configured.",
                        "actions_taken": []}
            lines = ["Hermes clients:"]
            for name, rec in sorted(clients.items()):
                state = "active" if rec.get("enabled", True) else "disabled"
                lines.append(f"  • {name} — {state}, "
                             f"created {rec.get('created', '?')}")
            return {"success": True, "response": "\n".join(lines),
                    "actions_taken": []}

        # -- default: status --
        with self._lock:
            stats = dict(self._stats)
        binds = ", ".join(f"{h}:{p}" for h, p in self._parse_binds())
        n_clients = len(self._load_clients())
        status = "🟢 Running" if running else "🔴 Stopped"
        lines = [
            f"Hermes API: {status}",
            f"Binds: {binds or '(none configured)'}",
            f"Clients: {n_clients}",
            f"Requests served: {stats['requests_served']}",
            f"Auth failures: {stats['auth_failures']}",
        ]
        if stats["last_seen"]:
            lines.append(f"Last request: {stats['last_seen']} "
                         f"from '{stats['last_client']}'")
        return {"success": True, "response": "\n".join(lines),
                "actions_taken": []}

    @staticmethod
    def _extract_client_name(command: str) -> str | None:
        """Pull the client name from 'add/revoke hermes client <name>'."""
        words = command.split()
        lowered = [w.lower().strip(".,'\"") for w in words]
        for anchor in ("client", "hermes"):
            if anchor in lowered:
                idx = len(lowered) - 1 - lowered[::-1].index(anchor)
                tail = [w.strip(".,'\"") for w in words[idx + 1:]
                        if w.lower().strip(".,'\"")
                        not in ("client", "called", "named", "key")]
                if tail:
                    return "-".join(tail).lower()
        return None


# ── HTTP handler ──────────────────────────────────────────────────────────────

class _HermesHandler(BaseHTTPRequestHandler):
    """OpenAI-compatible request handler. `_talent` is bound per server."""

    _talent: HermesApiTalent = None  # type: ignore[assignment]
    protocol_version = "HTTP/1.1"

    # Route http.server's chatty logging into our logger at debug level.
    def log_message(self, fmt, *args):  # noqa: N802
        log.debug("[Hermes][http] " + fmt % args)

    # -- helpers --

    def _json(self, code: int, obj: dict, extra_headers: dict | None = None):
        body = json.dumps(obj).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        for k, v in (extra_headers or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def _error(self, code: int, message: str, err_type: str):
        extra = {"WWW-Authenticate": "Bearer"} if code == 401 else None
        self._json(code, {"error": {"message": message, "type": err_type,
                                    "code": code}}, extra)

    def _authed_client(self) -> str | None:
        auth = self.headers.get("Authorization", "")
        if auth.startswith("Bearer "):
            name = self._talent.authenticate(auth[len("Bearer "):].strip())
            if name:
                return name
        self._talent.note_auth_failure(self.client_address[0])
        self._error(401, "Invalid or missing API key.",
                    "invalid_request_error")
        return None

    # -- routes --

    def do_GET(self):  # noqa: N802
        if self.path == "/health":
            self._json(200, {"status": "ok"})
            return
        if self.path in ("/v1/models", "/v1/models/"):
            if not self._authed_client():
                return
            self._json(200, {"object": "list", "data": [{
                "id": _MODEL_ID, "object": "model",
                "created": 0, "owned_by": "talon",
            }]})
            return
        self._error(404, f"Unknown path {self.path!r}.",
                    "invalid_request_error")

    def do_POST(self):  # noqa: N802
        if self.path not in ("/v1/chat/completions", "/v1/chat/completions/"):
            self._error(404, f"Unknown path {self.path!r}.",
                        "invalid_request_error")
            return

        client = self._authed_client()
        if not client:
            return

        try:
            length = int(self.headers.get("Content-Length", 0))
        except ValueError:
            length = 0
        if length <= 0 or length > _MAX_BODY_BYTES:
            self._error(413 if length > _MAX_BODY_BYTES else 400,
                        "Body missing or too large.", "invalid_request_error")
            return

        try:
            payload = json.loads(self.rfile.read(length).decode(
                "utf-8", errors="replace"))
        except json.JSONDecodeError:
            self._error(400, "Body is not valid JSON.",
                        "invalid_request_error")
            return

        user_text = self._last_user_text(payload.get("messages"))
        if not user_text:
            self._error(400, "No user message found in 'messages'.",
                        "invalid_request_error")
            return

        log.info(f"[Hermes] {client!r} → {user_text[:120]!r}")
        try:
            content, finish = self._talent.handle_chat(client, user_text)
        except Exception as e:
            log.error(f"[Hermes] handle_chat failed: {e}")
            self._error(500, "Talon failed to process the request.",
                        "server_error")
            return

        created = int(time.time())
        comp_id = "chatcmpl-" + secrets.token_hex(12)
        usage = {
            "prompt_tokens": max(1, len(user_text) // 4),
            "completion_tokens": max(1, len(content) // 4),
            "total_tokens": max(2, (len(user_text) + len(content)) // 4),
        }

        if payload.get("stream"):
            self._stream_response(comp_id, created, content, finish)
            return

        self._json(200, {
            "id": comp_id,
            "object": "chat.completion",
            "created": created,
            "model": _MODEL_ID,
            "choices": [{
                "index": 0,
                "message": {"role": "assistant", "content": content},
                "finish_reason": finish,
            }],
            "usage": usage,
        })

    # -- protocol details --

    @staticmethod
    def _last_user_text(messages) -> str:
        """Extract the latest user message; supports string and parts content."""
        if not isinstance(messages, list):
            return ""
        for msg in reversed(messages):
            if not isinstance(msg, dict) or msg.get("role") != "user":
                continue
            content = msg.get("content")
            if isinstance(content, str):
                return content.strip()
            if isinstance(content, list):   # multimodal parts format
                texts = [p.get("text", "") for p in content
                         if isinstance(p, dict) and p.get("type") == "text"]
                return "\n".join(t for t in texts if t).strip()
        return ""

    def _stream_response(self, comp_id: str, created: int,
                         content: str, finish: str) -> None:
        """Minimal SSE: the full reply as one delta chunk, then DONE.

        Talon's pipeline produces complete responses (no token stream to
        forward), so this exists purely for clients that insist on
        stream=true.
        """
        def chunk(delta: dict, finish_reason=None) -> bytes:
            return ("data: " + json.dumps({
                "id": comp_id, "object": "chat.completion.chunk",
                "created": created, "model": _MODEL_ID,
                "choices": [{"index": 0, "delta": delta,
                             "finish_reason": finish_reason}],
            }) + "\n\n").encode("utf-8")

        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "close")
        self.end_headers()
        try:
            self.wfile.write(chunk({"role": "assistant", "content": content}))
            self.wfile.write(chunk({}, finish_reason=finish))
            self.wfile.write(b"data: [DONE]\n\n")
        except (BrokenPipeError, ConnectionError):
            pass
