"""News digest talent — aggregate RSS feeds into a dated HTML file.

Config in settings.json under "news_digest":
  {
    "output_dir":           "",          // defaults to ~/talon_news/
    "max_stories_per_feed": 8,
    "max_age_hours":        24,
    "feeds": [
      {"name": "Reuters",  "url": "https://...", "category": "General"},
      ...
    ]
  }

Trigger phrases:  "generate morning news digest", "morning briefing",
                  "daily news", "collect news", etc.
"""
from __future__ import annotations

import json
import os
import re
import time
import datetime
import webbrowser

from talents.base import BaseTalent

_CONFIG_PATH = os.path.join("config", "news_digest.json")

# ── HTML helpers ──────────────────────────────────────────────────────────────

_CATEGORY_ORDER = ["General", "Technology", "Infosec", "Finance", "Science", "Sports"]

_CATEGORY_COLORS = {
    "general":    ("#3a7bd5", "#fff"),
    "technology": ("#2ecc71", "#fff"),
    "infosec":    ("#e74c3c", "#fff"),
    "finance":    ("#f1c40f", "#111"),
    "science":    ("#9b59b6", "#fff"),
    "sports":     ("#e67e22", "#fff"),
}
_DEFAULT_COLOR = ("#555577", "#fff")

_HTML_HEAD = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Talon News Digest &mdash; {date}</title>
<style>
  :root {{
    --bg: #0f1117; --surface: #1a1d27; --border: #2a2d3e;
    --text: #e0e0e8; --muted: #8888aa; --accent: #5a9cf8;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text);
          font-family: 'Segoe UI', system-ui, sans-serif;
          padding: 24px; max-width: 960px; margin: 0 auto; }}
  header {{ border-bottom: 1px solid var(--border); padding-bottom: 16px; margin-bottom: 28px; }}
  header h1 {{ font-size: 1.6rem; font-weight: 600; }}
  header p  {{ color: var(--muted); font-size: 0.88rem; margin-top: 4px; }}
  .section {{ margin-bottom: 36px; }}
  .section-label {{
    display: inline-block; font-size: 0.72rem; font-weight: 700;
    letter-spacing: 0.1em; text-transform: uppercase;
    padding: 3px 12px; border-radius: 4px; margin-bottom: 14px;
  }}
  .source-block {{
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 8px; margin-bottom: 14px; overflow: hidden;
  }}
  .source-name {{
    padding: 9px 16px; border-bottom: 1px solid var(--border);
    font-size: 0.82rem; font-weight: 600; color: var(--muted);
    letter-spacing: 0.03em;
  }}
  .story {{
    padding: 10px 16px; border-bottom: 1px solid var(--border);
    display: flex; flex-direction: column; gap: 4px;
  }}
  .story:last-child {{ border-bottom: none; }}
  .story-title {{ display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; }}
  .story-title a {{ color: var(--accent); text-decoration: none; font-size: 0.93rem; }}
  .story-title a:hover {{ text-decoration: underline; }}
  .story-age {{ font-size: 0.72rem; color: #666; white-space: nowrap; }}
  .story-summary {{ color: var(--muted); font-size: 0.81rem; line-height: 1.45; }}
  footer {{ text-align: center; color: #444; font-size: 0.78rem;
            margin-top: 36px; padding-top: 16px; border-top: 1px solid var(--border); }}
</style>
</head>
<body>
<header>
  <h1>&#128240; Talon News Digest</h1>
  <p>Generated {datetime_str} &nbsp;&middot;&nbsp; {story_count} stories &nbsp;&middot;&nbsp; {feed_count} sources</p>
</header>
"""

_HTML_FOOT = """\
<footer>Generated by Talon Assistant</footer>
</body>
</html>
"""

# ── helpers ───────────────────────────────────────────────────────────────────

def _age_label(ts: float) -> str:
    diff = time.time() - ts
    if diff < 3600:
        return f"{int(diff / 60)}m ago"
    elif diff < 86400:
        return f"{int(diff / 3600)}h ago"
    return f"{int(diff / 86400)}d ago"


def _esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


# ── talent ────────────────────────────────────────────────────────────────────

class NewsDigestTalent(BaseTalent):
    name        = "news_digest"
    description = (
        "Generate a dated HTML news digest from multiple RSS feeds and open it in the browser. "
        "Aggregates general news, technology, and infosec stories into one page."
    )
    keywords    = ["morning", "digest", "briefing", "daily news", "collect news",
                   "news brief", "daily brief"]
    examples    = [
        "generate morning news digest",
        "morning briefing",
        "daily news digest",
        "collect today's news",
        "run the morning digest",
        "give me a news briefing",
        "generate my daily briefing",
        "today's news summary",
    ]
    priority = 55   # above web_browser (47), below planner (85)

    # ── lifecycle ─────────────────────────────────────────────────────────────

    def get_config_schema(self) -> dict:
        return {
            "fields": [
                {"key": "output_dir",           "label": "Output Directory",
                 "type": "string",  "default": "",
                 "description": "Leave empty to use ~/talon_news/"},
                {"key": "max_stories_per_feed", "label": "Max Stories per Feed",
                 "type": "int",     "default": 8,  "min": 1, "max": 50},
                {"key": "max_age_hours",        "label": "Max Story Age (hours)",
                 "type": "int",     "default": 24, "min": 1, "max": 168},
                {"key": "feeds",                "label": "RSS Feeds",
                 "type": "feed_table", "default": []},
            ]
        }

    def initialize(self, config: dict) -> None:
        nd = config.get("news_digest", {})
        self._apply_config(nd)

    def update_config(self, config: dict) -> None:
        """Called by the UI when the user saves changes in the talent config dialog."""
        super().update_config(config)
        self._apply_config(config)
        self._save_config(config)

    def _apply_config(self, nd: dict) -> None:
        self._output_dir  = nd.get("output_dir", "")
        self._max_stories = int(nd.get("max_stories_per_feed", 8))
        self._max_age_h   = float(nd.get("max_age_hours", 24))
        all_feeds         = nd.get("feeds", [])
        # Only fetch feeds the user has enabled
        self._feeds       = [f for f in all_feeds if f.get("enabled", True)]
        if all_feeds:
            print(f"[NewsDigest] {len(self._feeds)}/{len(all_feeds)} feed(s) enabled.")
        else:
            print("[NewsDigest] Warning: no feeds in news_digest.json")

    def _save_config(self, config: dict) -> None:
        """Persist feed changes back to config/news_digest.json."""
        try:
            # Read existing file so we don't lose keys we don't manage
            existing = {}
            if os.path.exists(_CONFIG_PATH):
                with open(_CONFIG_PATH, "r", encoding="utf-8") as f:
                    existing = json.load(f)
            existing.update({
                "output_dir":           config.get("output_dir", ""),
                "max_stories_per_feed": config.get("max_stories_per_feed", 8),
                "max_age_hours":        config.get("max_age_hours", 24),
                "feeds":                config.get("feeds", []),
            })
            with open(_CONFIG_PATH, "w", encoding="utf-8") as f:
                json.dump(existing, f, indent=2, ensure_ascii=False)
            print(f"[NewsDigest] Config saved to {_CONFIG_PATH}")
        except Exception as e:
            print(f"[NewsDigest] Failed to save config: {e}")

    def can_handle(self, command: str) -> bool:
        return self.keyword_match(command)

    # ── execute ───────────────────────────────────────────────────────────────

    def execute(self, command: str, context: dict) -> dict:
        speak  = context.get("speak_response", True)
        voice  = context.get("voice")

        if not self._feeds:
            msg = ("No news feeds configured. "
                   "Add feeds to settings.json under 'news_digest.feeds'.")
            if speak and voice:
                voice.speak(msg)
            return {"success": False, "response": msg, "actions_taken": []}

        # ── fetch ─────────────────────────────────────────────────────────────
        print(f"[NewsDigest] Fetching {len(self._feeds)} feed(s)…")
        categories: dict[str, list[dict]] = {}

        for feed_cfg in self._feeds:
            name     = feed_cfg.get("name", "Unknown")
            url      = feed_cfg.get("url", "")
            category = feed_cfg.get("category", "General").title()
            if not url:
                continue
            stories = self._fetch_feed(url, name)
            if not stories:
                print(f"   [NewsDigest] {name}: no stories (feed unavailable or all old)")
                continue
            categories.setdefault(category, []).append(
                {"source": name, "url": url, "stories": stories}
            )
            print(f"   [NewsDigest] {name}: {len(stories)} stories")

        if not categories:
            msg = "Couldn't fetch any news stories right now — feeds may be unavailable."
            if speak and voice:
                voice.speak(msg)
            return {"success": False, "response": msg, "actions_taken": []}

        # ── render HTML ───────────────────────────────────────────────────────
        story_count = sum(
            len(sg["stories"]) for groups in categories.values() for sg in groups
        )
        feed_count = sum(len(v) for v in categories.values())
        now          = datetime.datetime.now()
        date_str     = now.strftime("%B %d, %Y")
        datetime_str = now.strftime("%B %d, %Y at %I:%M %p")
        filename     = now.strftime("%Y%m%d") + ".html"

        html = _HTML_HEAD.format(
            date=date_str,
            datetime_str=datetime_str,
            story_count=story_count,
            feed_count=feed_count,
        )

        # Sections in preferred order, then any unlisted categories
        all_cats = list(categories.keys())
        ordered  = [c for c in _CATEGORY_ORDER if c in all_cats]
        ordered += [c for c in all_cats if c not in ordered]

        for cat in ordered:
            key        = cat.lower()
            bg, fg     = _CATEGORY_COLORS.get(key, _DEFAULT_COLOR)
            html += f'<div class="section">\n'
            html += (f'  <div class="section-label" '
                     f'style="background:{bg};color:{fg}">{_esc(cat)}</div>\n')
            for sg in categories[cat]:
                html += f'  <div class="source-block">\n'
                html += f'    <div class="source-name">&#128225; {_esc(sg["source"])}</div>\n'
                for story in sg["stories"]:
                    title   = _esc(story.get("title", ""))
                    link    = story.get("link", "#")
                    summary = _esc(story.get("summary", ""))
                    age     = _esc(story.get("age", ""))
                    html += f'    <div class="story">\n'
                    html += f'      <div class="story-title">\n'
                    html += f'        <a href="{link}" target="_blank">{title}</a>\n'
                    if age:
                        html += f'        <span class="story-age">{age}</span>\n'
                    html += f'      </div>\n'
                    if summary:
                        html += f'      <div class="story-summary">{summary}</div>\n'
                    html += f'    </div>\n'
                html += f'  </div>\n'
            html += f'</div>\n'

        html += _HTML_FOOT

        # ── save ──────────────────────────────────────────────────────────────
        out_dir = self._output_dir or os.path.join(os.path.expanduser("~"), "talon_news")
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, filename)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"[NewsDigest] Saved → {out_path}")

        # ── open ──────────────────────────────────────────────────────────────
        webbrowser.open(f"file:///{out_path.replace(os.sep, '/')}")

        msg = (f"Morning digest ready — {story_count} stories from {feed_count} sources. "
               f"Opening in your browser.")
        if speak and voice:
            voice.speak(msg)
        return {
            "success":       True,
            "response":      msg,
            "actions_taken": [{"action": "news_digest", "path": out_path,
                               "stories": story_count, "sources": feed_count}],
        }

    # ── RSS fetcher ───────────────────────────────────────────────────────────

    def _fetch_feed(self, url: str, name: str) -> list[dict]:
        """Fetch a single RSS feed; returns a list of story dicts sorted newest-first."""
        try:
            import feedparser
        except ImportError:
            print("[NewsDigest] feedparser not installed — run: pip install feedparser")
            return []

        try:
            feed    = feedparser.parse(url)
            entries = feed.entries
            if not entries:
                return []

            cutoff  = time.time() - self._max_age_h * 3600
            stories = []

            for entry in entries:
                t  = entry.get("published_parsed") or entry.get("updated_parsed")
                ts = time.mktime(t) if t else None

                # Drop stories older than max_age_hours (when we have a timestamp)
                if ts is not None and ts < cutoff:
                    continue

                title   = entry.get("title",   "").strip()
                link    = entry.get("link",    "#")
                summary = re.sub(r'<[^>]+>', '', entry.get("summary", "")).strip()
                if len(summary) > 220:
                    summary = summary[:220].rsplit(" ", 1)[0] + "\u2026"

                if title:
                    stories.append({
                        "title":   title,
                        "link":    link,
                        "summary": summary,
                        "age":     _age_label(ts) if ts else "",
                        "ts":      ts or 0.0,
                    })

                if len(stories) >= self._max_stories:
                    break

            stories.sort(key=lambda s: s["ts"], reverse=True)
            return stories

        except Exception as e:
            print(f"   [NewsDigest] Error fetching {name} ({url}): {e}")
            return []
